### ISSUE TITLE
Sending a stop scan and deleting a scan on a low-end machine will fail

### ISSUE THREAD

**Issue by wrenchonline** [greenbone/ospd-openvas#953] opened 2023-11-29 01:35 UTC
ospd-openvas 22.6.0
OpenVAS 22.7.5
gvm-libs 22.7.1
Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
virtual machine  VMware   CPU resource allocation, dual core

**Comment by ArnoStiefvater** [comment] 2023-11-29 05:14
Hey @wrenchonline,

Thanks for creating the issue but can you please provide some more information?

What is the error message or logs, how do you know that deleting the scan does not work?
Why do you think it has something todo with low-end machines? Does this not happen for your other machines?
Are you using the web frontend (GSA with backend gvmd) or are you using ospd-openvas directly?

**Comment by wrenchonline** [comment] 2023-11-30 02:04
> Hey @wrenchonline,
> 
> Thanks for creating the issue but can you please provide some more information?
> 
> What is the error message or logs, how do you know that deleting the scan does not work? Why do you think it has something todo with low-end machines? Does this not happen for your other machines? Are you using the web frontend (GSA with backend gvmd) or are you using ospd-openvas directly?
Yes, scanning a single IP can stop, but scanning a network segment will prompt a timeout
![DC16E4AEC92A7381673431BF6BE12F77](https://github.com/greenbone/ospd-openvas/assets/35405471/995d4dac-2ce6-460e-81e8-a10ec3ba4254)

**Comment by ArnoStiefvater** [comment] 2023-11-30 08:17
Jira tracking: SC-966

**Comment by ArnoStiefvater** [comment] 2023-12-20 03:07
Hey,

I am closing this issue as we are not able to reproduce the issue and the provided information does not give us enough inside into the problem.

**Closed by ArnoStiefvater** 2023-12-20 03:07 UTC
Labels: bug
