### ISSUE TITLE
ospd-openvas:22.4.6 - scan process never stop

### ISSUE THREAD

**Issue by Bepsi** [greenbone/ospd-openvas#884] opened 2023-04-06 13:27 UTC
Hi,
I use GVM Community containers 22.4 (https://greenbone.github.io/docs/latest/22.4/container/index.html).
When I run a scan, everything works perfectly ... except when the scan ends. The "openvas --scan-start" process never stops even though the task is done under GSA.

Log ospd-openvas container:
06/04/2023 14:32:32OSPD[1] 2023-04-06 12:32:32,624: DEBUG: (ospd.ospd) 3f2f4d82-83ec-47ca-9728-c07a2cd103cd: Current scan status: FINISHED,

docker top 
*UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
gvm                 19793               19772               6                   13:49               pts/0               00:02:58            /usr/bin/python3 /usr/local/bin/ospd-openvas -f --config /etc/gvm/ospd-openvas.conf --mqtt-broker-address mqtt-broker --notus-feed-dir /var/lib/notus/advisories-m 666
gvm                 19874               19793               0                   13:49               pts/0               00:00:17            /usr/bin/python3 /usr/local/bin/ospd-openvas -f --config /etc/gvm/ospd-openvas.conf --mqtt-broker-address mqtt-broker --notus-feed-dir /var/lib/notus/advisories-m 666
gvm                 31298               19793               10                  14:15               ?                   00:01:52            openvas --scan-start 3f2f4d82-83ec-47ca-9728-c07a2cd103cd

**Comment by cfi-gb** [comment] 2023-09-04 14:50
Based on the description this sounds like a duplicate of:
- greenbone/openvas-scanner#1271

**Comment by ChristianPraiss** [comment] 2024-12-12 14:28
It seems the issue has been fixed in openvas, I can confirm the behaviour disappeared in the latest `edge` build, but I supposed releasing a new version of the `ospd-openvas` docker image could make sense to prevent new users from encountering this issue in the currently published version, which still version 23.0.2 of the openvas binary.

**Closed** 2024-12-23 17:24 UTC
Labels: bug

**Comment by jjnicola** [comment] 2025-01-08 12:46
@ChristianPraiss New image has been build. Regards!
