### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by pomac303** [greenbone/ospd-openvas#180] opened 2020-01-14 12:10 UTC
In ospd-openvas 1.0.0, i worked around it with if None == timeout: timeout = 120 to continue testing

jan 14 10:50:24 openvas ospd-openvas[16659]: Traceback (most recent call last):
                                               File "/usr/bin/ospd-openvas", line 11, in <module>
                                                 load_entry_point('ospd-openvas==1.0.0', 'console_scripts', 'ospd-openvas')()
                                               File "/usr/lib/python3/dist-packages/ospd_openvas/daemon.py", line 1454, in main
                                                 daemon_main('OSPD - openvas', OSPDopenvas)
                                               File "/usr/lib/python3/dist-packages/ospd/main.py", line 159, in main
                                                 daemon.init()
                                               File "/usr/lib/python3/dist-packages/ospd_openvas/daemon.py", line 293, in init
                                                 self.load_vts()
                                               File "/usr/lib/python3/dist-packages/ospd_openvas/daemon.py", line 410, in load_vts
                                                 _vt_params = self.nvti.get_nvt_params(vt_id)
                                               File "/usr/lib/python3/dist-packages/ospd_openvas/nvticache.py", line 82, in get_nvt_params
                                                 if int(timeout) > 0:
                                             TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by j-licht** [comment] 2020-03-25 19:43
I've experienced the same problem.
I think it's caused by a missing key in the redis DB.
As I found in my redis.conf the default of maxmemory is 64MB and after that redis will drop keys.
So removing this config line solves the problem for me.

**Comment by jjnicola** [comment] 2020-03-26 07:29
Hi @j-licht ,
@pomac303 had reported also the issue #179. I think this issue is related to that one. Could you check please your python-redis version?

**Comment by pomac303** [comment] 2020-03-26 10:53
No maxmemory was set - bumped it to 10gb - scan is stuck at 3% even if the nmap processes are done (after 1 day)

**Comment by j-licht** [comment] 2020-03-26 11:18
It works fine for me with python-redis version 3.2.1 and 3.3.11.
@pomac303 I get the knowledge about missing redis keys by printing all queries in the timeout request and check then with the redis-cli.

**Comment by tuxmaster5000** [comment] 2020-05-05 07:03
I have the same problem. Where can I see if redis drops key's?
At /var/log/redis/redis.log I don't see any messages about it.
I use redis-3.3.11 of the python bindings.

**Comment by jjnicola** [comment] 2021-03-03 13:15
Ospd-openvas has changed a lot since v20.08 in the way it handles the VTs. Currently it doesn't use the interal VT storage and communicates directly with redis. This issue is not present anymore in the current stable version. For references about this changes see PR #236.
Therefore I close the issue here.

**Closed by jjnicola** 2021-03-03 13:15 UTC
Labels: feedback required
